In [128]:
import sqlite3
import pandas as pd

In [129]:
from google.colab import files
uploaded = files.upload()

Saving hr_cleaned.csv to hr_cleaned (2).csv

In [130]:
clean_df=pd.read_csv("hr_cleaned.csv")

In [131]:
clean_df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeNumber,EnvironmentSatisfaction,...,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Age_Group,Income_Band,Tenure_Bucket,Attrition_Flag,OverTime_Flag
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,2,...,1,6,4,0,5,36-45,High,6-10 Years,1,1
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,2,3,...,3,10,7,1,7,46-55,High,6-10 Years,0,0
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,4,4,...,3,0,0,0,0,36-45,Low,0-2 Years,1,1
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,5,4,...,3,8,7,3,0,26-35,Low,6-10 Years,0,1
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,7,1,...,3,2,2,2,2,26-35,Medium,0-2 Years,0,0

In [132]:
conn=sqlite3.connect("people_analytics.db")

In [133]:
clean_df.to_sql(
    "employees",
    conn,
    if_exists="replace",
    index=False
)

1470

In [134]:
query = """
SELECT COUNT(*)
FROM employees
"""
pd.read_sql(query,conn)

   COUNT(*)
0      1470

In [135]:
query="""
SELECT *
FROM employees
LIMIT 5
"""
pd.read_sql(query,conn)

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeNumber,EnvironmentSatisfaction,...,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Age_Group,Income_Band,Tenure_Bucket,Attrition_Flag,OverTime_Flag
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,2,...,1,6,4,0,5,36-45,High,6-10 Years,1,1
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,2,3,...,3,10,7,1,7,46-55,High,6-10 Years,0,0
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,4,4,...,3,0,0,0,0,36-45,Low,0-2 Years,1,1
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,5,4,...,3,8,7,3,0,26-35,Low,6-10 Years,0,1
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,7,1,...,3,2,2,2,2,26-35,Medium,0-2 Years,0,0

In [136]:
query="""
PRAGMA table_info(employees)
"""
pd.read_sql(query,conn)

    cid                      name     type  notnull dflt_value  pk
0     0                       Age  INTEGER        0       None   0
1     1                 Attrition     TEXT        0       None   0
2     2            BusinessTravel     TEXT        0       None   0
3     3                 DailyRate  INTEGER        0       None   0
4     4                Department     TEXT        0       None   0
5     5          DistanceFromHome  INTEGER        0       None   0
6     6                 Education  INTEGER        0       None   0
7     7            EducationField     TEXT        0       None   0
8     8            EmployeeNumber  INTEGER        0       None   0
9     9   EnvironmentSatisfaction  INTEGER        0       None   0
10   10                    Gender     TEXT        0       None   0
11   11                HourlyRate  INTEGER        0       None   0
12   12            JobInvolvement  INTEGER        0       None   0
13   13                  JobLevel  INTEGER        0       None   0
14   14                   JobRole     TEXT        0       None   0
15   15           JobSatisfaction  INTEGER        0       None   0
16   16             MaritalStatus     TEXT        0       None   0
17   17             MonthlyIncome  INTEGER        0       None   0
18   18               MonthlyRate  INTEGER        0       None   0
19   19        NumCompaniesWorked  INTEGER        0       None   0
20   20                  OverTime     TEXT        0       None   0
21   21         PercentSalaryHike  INTEGER        0       None   0
22   22         PerformanceRating  INTEGER        0       None   0
23   23  RelationshipSatisfaction  INTEGER        0       None   0
24   24          StockOptionLevel  INTEGER        0       None   0
25   25         TotalWorkingYears  INTEGER        0       None   0
26   26     TrainingTimesLastYear  INTEGER        0       None   0
27   27           WorkLifeBalance  INTEGER        0       None   0
28   28            YearsAtCompany  INTEGER        0       None   0
29   29        YearsInCurrentRole  INTEGER        0       None   0
30   30   YearsSinceLastPromotion  INTEGER        0       None   0
31   31      YearsWithCurrManager  INTEGER        0       None   0
32   32                 Age_Group     TEXT        0       None   0
33   33               Income_Band     TEXT        0       None   0
34   34             Tenure_Bucket     TEXT        0       None   0
35   35            Attrition_Flag  INTEGER        0       None   0
36   36             OverTime_Flag  INTEGER        0       None   0

In [137]:
query="""
SELECT COUNT(*) AS Total_Employees
FROM employees
"""
pd.read_sql(query,conn)

   Total_Employees
0             1470

In [138]:
query="""
SELECT DISTINCT Department
FROM employees
"""
pd.read_sql(query,conn)

               Department
0                   Sales
1  Research & Development
2         Human Resources

In [139]:
query="""
SELECT
  Department,
  COUNT(*) AS Employee_Count
FROM employees
GROUP BY Department;
"""
pd.read_sql(query,conn)

               Department  Employee_Count
0         Human Resources              63
1  Research & Development             961
2                   Sales             446

In [140]:
query="""
SELECT Department,ROUND(AVG(MonthlyIncome),2) AS Average_Salary
FROM employees
GROUP BY Department
"""
pd.read_sql(query,conn)

               Department  Average_Salary
0         Human Resources         6654.51
1  Research & Development         6281.25
2                   Sales         6959.17

In [141]:
query="""
SELECT Attrition,COUNT(*) AS Employees
FROM employees
GROUP BY Attrition
"""
pd.read_sql(query,conn)

  Attrition  Employees
0        No       1233
1       Yes        237

In [142]:
query="""
SELECT OverTime,COUNT(*) AS Employees
FROM employees
GROUP BY OverTime;
"""
pd.read_sql(query,conn)

  OverTime  Employees
0       No       1054
1      Yes        416

In [143]:
query="""
SELECT EmployeeNumber,JobRole,MonthlyIncome
FROM employees
ORDER BY MonthlyIncome DESC
LIMIT 10;
"""
pd.read_sql(query,conn)

   EmployeeNumber            JobRole  MonthlyIncome
0             259            Manager          19999
1            1035  Research Director          19973
2            1191            Manager          19943
3             226            Manager          19926
4             787            Manager          19859
5            1282            Manager          19847
6            1038            Manager          19845
7            1740            Manager          19833
8            1255  Research Director          19740
9            1338            Manager          19717

In [144]:
query="""
SELECT Age_Group,COUNT(*) AS Employees
FROM employees
GROUP BY Age_Group;
"""
pd.read_sql(query,conn)

  Age_Group  Employees
0     18-25        123
1     26-35        606
2     36-45        468
3     46-55        226
4       56+         47

In [145]:
query="""
SELECT Income_Band,COUNT(*) AS Employees
FROM employees
GROUP BY Income_Band;
"""
pd.read_sql(query,conn)

  Income_Band  Employees
0   Executive        368
1        High        367
2         Low        369
3      Medium        366

In [146]:
query="""
SELECT Tenure_Bucket,COUNT(*) AS Employees
FROM employees
GROUP BY Tenure_Bucket;
"""
pd.read_sql(query,conn)

  Tenure_Bucket  Employees
0     0-2 Years        342
1     10+ Years        246
2     3-5 Years        434
3    6-10 Years        448

In [147]:
conn.close()

In [148]:
import sqlite3
import pandas as pd
conn=sqlite3.connect("people_analytics.db")
clean_df=pd.read_sql("SELECT * FROM employees",conn)

In [149]:
clean_df["Employee_ID"]=[f"{str(i).zfill(4)}"
  for i in range(1,len(clean_df)+1)]

In [150]:
clean_df[["EmployeeNumber","Employee_ID"]].head()

   EmployeeNumber Employee_ID
0               1        0001
1               2        0002
2               4        0003
3               5        0004
4               7        0005

In [151]:
clean_df["Career_Stagnation_Index"]=(clean_df["YearsSinceLastPromotion"]/(clean_df["YearsAtCompany"]+1)).round(2)

In [152]:
clean_df["Promotion_Delay_Risk"]=(clean_df["YearsSinceLastPromotion"]>=5).astype(int)

In [153]:
clean_df["Workload_Risk"]=(
    (
        clean_df["OverTime_Flag"]==1
    )&
    (
        clean_df["WorkLifeBalance"]<=2
    )
).astype(int)

In [154]:
clean_df["Compensation_Risk"]=(
    clean_df["Income_Band"]=="Low"
).astype(int)

In [155]:
clean_df["Travel_Risk"]=(
    clean_df["BusinessTravel"]=="Travel_Frequently"
).astype(int)

In [156]:
clean_df["Satisfaction_Risk"]=(
    (
        clean_df["JobSatisfaction"]<=2
    )&
    (
        clean_df["EnvironmentSatisfaction"]<=2
    )
).astype(int)

In [157]:
risk_columns=[
    "Promotion_Delay_Risk",
    "Workload_Risk",
    "Compensation_Risk",
    "Travel_Risk",
    "Satisfaction_Risk"
]
clean_df["HR_Risk_Score"]=clean_df[risk_columns].sum(axis=1)

In [158]:
clean_df["HR_Risk_Level"]=pd.cut(
    clean_df["HR_Risk_Score"],
    bins=[-0.1,1.5,3.5,5.5],
    labels=["Low","Medium","High"]
)

In [159]:
clean_df[[
    "Employee_ID",
    "Career_Stagnation_Index",
    "Promotion_Delay_Risk",
    "Workload_Risk",
    "Compensation_Risk",
    "Travel_Risk",
    "Satisfaction_Risk",
    "HR_Risk_Score",
    "HR_Risk_Level"
]].head(10)

,Employee_ID,Career_Stagnation_Index,Promotion_Delay_Risk,Workload_Risk,Compensation_Risk,Travel_Risk,Satisfaction_Risk,HR_Risk_Score,HR_Risk_Level
0,0001,0.00,0,1,0,0,0,1,Low
1,0002,0.09,0,0,0,1,0,1,Low
2,0003,0.00,0,0,1,0,0,1,Low
3,0004,0.33,0,0,1,1,0,2,Medium
4,0005,0.67,0,0,0,0,1,1,Low
5,0006,0.38,0,0,0,1,0,1,Low
6,0007,0.00,0,1,1,0,0,2,Medium
7,0008,0.00,0,0,1,0,0,1,Low
8,0009,0.10,0,0,0,1,0,1,Low
9,0010,0.88,1,0,0,0,0,1,Low

In [160]:
risk_columns=[
    "Promotion_Delay_Risk",
    "Workload_Risk",
    "Compensation_Risk",
    "Travel_Risk",
    "Satisfaction_Risk"
]
clean_df[risk_columns].head(10)

,Promotion_Delay_Risk,Workload_Risk,Compensation_Risk,Travel_Risk,Satisfaction_Risk
0,0,1,0,0,0
1,0,0,0,1,0
2,0,0,1,0,0
3,0,0,1,1,0
4,0,0,0,0,1
5,0,0,0,1,0
6,0,1,1,0,0
7,0,0,1,0,0
8,0,0,0,1,0
9,1,0,0,0,0

In [161]:
clean_df[risk_columns].isnull().sum()

Promotion_Delay_Risk    0
Workload_Risk           0
Compensation_Risk       0
Travel_Risk             0
Satisfaction_Risk       0
dtype: int64

In [162]:
clean_df[risk_columns].dtypes

Promotion_Delay_Risk    int64
Workload_Risk           int64
Compensation_Risk       int64
Travel_Risk             int64
Satisfaction_Risk       int64
dtype: object

In [163]:
clean_df["HR_Risk_Score"]=clean_df[risk_columns].fillna(0).sum(axis=1)

In [164]:
clean_df[["HR_Risk_Score"]].head(10)

   HR_Risk_Score
0              1
1              1
2              1
3              2
4              1
5              1
6              2
7              1
8              1
9              1

In [165]:
clean_df["HR_Risk_Level"]=pd.cut(
    clean_df["HR_Risk_Score"],
    bins=[-0.1,1.5,3.5,5.5],
    labels=["Low","Medium","High"],
    include_lowest=True
)

In [166]:
clean_df[["HR_Risk_Score","HR_Risk_Level"]].head(10)

   HR_Risk_Score HR_Risk_Level
0              1           Low
1              1           Low
2              1           Low
3              2        Medium
4              1           Low
5              1           Low
6              2        Medium
7              1           Low
8              1           Low
9              1           Low

In [167]:
risk_df=clean_df[["Employee_ID",
                  "Career_Stagnation_Index",
                  "Promotion_Delay_Risk",
                  "Workload_Risk",
                  "Compensation_Risk",
                  "Travel_Risk",
                  "Satisfaction_Risk",
                  "HR_Risk_Score",
                  "HR_Risk_Level"]]
risk_df.to_sql(
    "employee_risk",
    conn,
    if_exists="replace",
    index=False
)

1470

In [168]:
pd.read_sql("SELECT * FROM employee_risk LIMIT 5;",conn)

,Employee_ID,Career_Stagnation_Index,Promotion_Delay_Risk,Workload_Risk,Compensation_Risk,Travel_Risk,Satisfaction_Risk,HR_Risk_Score,HR_Risk_Level
0,0001,0.00,0,1,0,0,0,1,Low
1,0002,0.09,0,0,0,1,0,1,Low
2,0003,0.00,0,0,1,0,0,1,Low
3,0004,0.33,0,0,1,1,0,2,Medium
4,0005,0.67,0,0,0,0,1,1,Low

In [169]:
conn.execute("""
CREATE VIEW IF NOT EXISTS high_risk_employees AS
SELECT Employee_ID,HR_Risk_Score,HR_Risk_Level
FROM employee_risk
WHERE HR_Risk_Level='High';""")

In [170]:
pd.read_sql("SELECT * FROM high_risk_employees;",conn)

  Employee_ID  HR_Risk_Score HR_Risk_Level
0        0637              4          High
1        0890              4          High

In [171]:
conn.execute("""
CREATE VIEW IF NOT EXISTS department_summary AS
SELECT Department, COUNT(*) AS Employee_Count, ROUND(AVG(MonthlyIncome),2) AS Average_Income, ROUND(AVG(JobSatisfaction),2) AS Average_Job_Satisfaction
FROM employees
GROUP BY Department;
""")

In [172]:
pd.read_sql("SELECT * FROM department_summary;",conn)

,Department,Employee_Count,Average_Income,Average_Job_Satisfaction
0,Human Resources,63,6654.51,2.60
1,Research & Development,961,6281.25,2.73
2,Sales,446,6959.17,2.75

In [173]:
query="""
SELECT Department,ROUND(AVG(MonthlyIncome),2) AS Average_Income
FROM employees
GROUP BY Department
ORDER BY Average_Income DESC;
"""
pd.read_sql(query,conn)

               Department  Average_Income
0                   Sales         6959.17
1         Human Resources         6654.51
2  Research & Development         6281.25

In [174]:
query="""
SELECT JobRole,ROUND(AVG(YearsSinceLastPromotion),2) AS Average_Years_Since_Last_Promotion
FROM employees
GROUP BY JobRole
ORDER BY Average_Years_Since_Last_Promotion DESC;
"""
pd.read_sql(query,conn)

                     JobRole  Average_Years_Since_Last_Promotion
0                    Manager                                4.83
1          Research Director                                3.19
2  Healthcare Representative                                2.97
3            Sales Executive                                2.48
4     Manufacturing Director                                2.12
5         Research Scientist                                1.51
6      Laboratory Technician                                1.42
7            Human Resources                                1.27
8       Sales Representative                                1.06

In [175]:
query="""
SELECT Income_Band,COUNT(*) AS Employee_Count,ROUND(AVG(MonthlyIncome),2) AS Average_Income
FROM employees
GROUP BY Income_Band;
"""
pd.read_sql(query,conn)

  Income_Band  Employee_Count  Average_Income
0   Executive             368        13508.35
1        High             367         6181.74
2         Low             369         2354.13
3      Medium             366         3964.10

In [176]:
query="""
SELECT HR_Risk_Level,COUNT(*) AS Employee_Count, ROUND(AVG(HR_Risk_Score),2) AS Average_Risk_Score
FROM employee_risk
GROUP BY HR_Risk_Level;
"""
pd.read_sql(query,conn)
#

  HR_Risk_Level  Employee_Count  Average_Risk_Score
0          High               2                4.00
1           Low            1194                0.54
2        Medium             274                2.16

In [184]:
conn.close()